import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
 en:{
   login:"Login/Registration",
   login_button:"Join",
   password_length:"Password is too short - should be at least 6 symbol.",
   restore_password:"Forgot password",
   restore_button:"Restore",
   user_not_found:"User with this email not found please try another email or may be you are not registered",
   system_notification:"Notification",
   password_mail_notification:"The password has been sent to your email",
   company_name:"Enter company name",
   title_name:"Enter business url",
   description_name:"Description",
   description_placeholder:"Please write description about your business and what you want to hear from creators",
   location_name:"Enter address",
   location_error:"Please choose location",
   time_name:"Choose time",
   amount_name:"Amount ",
   amount_placeholder:"lets count how many creators will involved",
   date_name:"Start date",
   continue_button:"Continue",
   count_of_bloggers:"Involved creators count",
   count_of_subscribers:"Approximate coverage",
   choose_payment:"Please make a payment",
   request:"Request ",
   paid:"Paid ",
   approximate_reach:"Approximate reach ",
   involved_bloggers:"Involved Creators ",
   platforms_in_use:"Platforms in use ",
   tiktok:"Tiktok ",
   instagramm:"Instagram ",
   facebook:"Facebook ",
   twitter:"Twitter ",
   list_of_bloggers:"List of Creators ",
   view:"View",
   profile:"Profile",
   detail:"Detail",
   completition:"Details about completition",
   profileInformation:"Profile Information",
   number_of_c_tasks:"Number of Completed Tasks",
   rating:"Rating",
   subscribers_p:"Subscribers",
   rate:"Rate",
   rateDescribe:"please leave detail review",
   successAction:"Success action Thanks!",
   rateAction:"Please click star to rate!",
   cantRate:"You already rate..",
   selectRole:"Select your Role",
   blogger:"Creator",
   business:"Business",
   continue:"Continue?",
   no:"no",
   yes:"yes",
   currentStep:"create video about business and upload here: ",
   socialNetwork:" (social network) ",
   currentStepAfter:" copy link and insert below inside form, then click button 'next': ",
   doneTask:"Task Submitted",
   waitingApprove:"under consideration by business",
   Offers:"Offers",
   cancel:"cancel",
   check:"check",
   dialogCheckMessage:"You have new suggestion from business please go to Contacts to discuss",
   startTask:"Start task",
   CopyUrl:"Copy url",
   next_x:"Next",
   chat_with_business:"Chat with Business",
   select_social:"Select Social Network",
   edit_social:"Edit Box",
   confirm_edit:"Confirm",
   edit_confirmation:"this field only for update purpose, try field above to add new link if previous video was banned",
   replace_confirmation:"this video already exixt please add try another to remove banned video",
   edit_button_link:"Edit Video Link",
   banBoxTitle:"This videos were banned please make new videos and upload for this social networks and insert link above to form",
   onlyLocal:"Involve only local creators",
   highRank:"Work only with famous influencers",
   searchLocal:"Search only local business",
   newCompletedUser:"1 user completed task",
   PleaseCheckThisTask:"Please check this task ",
   PleaseImprove:"Please improve video ",
   Confirm_task:"Confirm task",
   UncorfimedTask:"You Have new unconfirmed task",
   Confirmed_task:"Task Confirmed",
   Go_offline:"Go offline",
   who_is:"please type",
   change_video_text:"Change video",
   Decline:"Decline task",
   Sign:"Sign in",
   Sign_up:"Sign up",
   Creator:"Creator",
   Business:"Business",
   Blogger:"BLOGERS",
   echohub_title:"is a new, effective way of spreading information through a network of pooled bloggers",
   All_rights_reserved:"All rights reserved",
   Follow_Twitter:"Follow us on Twitter",
   Follow_Youtube:"Follow us on Youtube",
   Follow_TikTok:"Follow us on TikTok",
   Follow_Facebook:"Follow us on Facebook",
   Follow_Instagram:"Follow us on Instagram",
   Privacy_policy:"Privacy policy",
   Denial_responsibility:"Denial of responsibility",
   Subscribe_to_news:"Subscribe to news",
   Reviews:"Reviews",
   About_Connect:"About Us, Connect",
   Patent_USA:"Patent - 1141, USA",
   Six:"6",
   number_of_subscribersM:"Numbers of subscribers,",
   locationM:"location",
   interestM:"interest",
   targetA:"the target audience",
   Large:"Large reach through a pool of bloggers helps",
   Make:"make your product or service recognizable!",
   Various:"Various types of influencers drive more intent to",
   VariousTwo:"purchase down the funnel and bring a strong ROI",
   Around:"Around 40% of people",
   reported:"reported that they",
   purchased:"purchased a product",
   online_M:"online after seeing | used",
   online_B:"by an influencer on",
   online_youtube:"Youtube, Instagram or",
   online_twitter:"twitter",
   our_main:"Our main focus is on nano-influencer",
   our_mainTwo:"and Micro Influencers.",
   marketers:"89% of marketers say",
   marketers2:"that ROI from influencer",
   marketers3:"marketing is",
   marketers4:"comparable to or better",
   marketers5:"than other marketing",
   marketers6:"channels",
   according:"According to a study by",
   according2:"Tomson, influencer",
   according3:"marketing yields a $ 6.50",
   according4:"return on investment for",
   according5:"every dollar spent",
   followers:"FOLLOWERS",
   they_would:"They would also be crusial to a local business",
   in_a:"in a particular area.",
   you_r:"You receive",
   content:"Content Quality",
   f_reach:"Follower Reach",
   eng:"Engagement",
   video_g:"Video generates 80% more conversion",
   cross_pr:"Cross promote with us",
   cross_two:"More engagement likes, and shares for your content",
   cross_three:"the process is more time-consuming but the ROI is worth it.",
   define:"Define core",
   defineTwo:"messages",
   send:"Send the compaign",
   sendTwo:"request in Echohub.io",
   cross:"Cross promoting",
   crossTwo:"can be pretty easy",
   views:"Views",
   viewsTwo:"Social impressions",
   viewsThree:"Clicks",
   millionN:"million",



 },
 it: {
   login:"Login/Registration",
   login_button:"Join",
   password_length:"Password is too short - should be at least 6 chars minimum.",
   restore_password:"Forgot password",
   restore_button:"Restore",
   user_not_found:"User with this email not found please try another email or may be you are not registered",
   system_notification:"Notification",
   password_mail_notification:"The password has been sent to your email",
   title_name:"Name of business or url",
   description_name:"Description",
   description_placeholder:"Please write description about your business and what you want to hear from creators",
   location_name:"Chose location",
   time_name:"Choose time",
   amount_name:"Amount",
   amount_placeholder:"lets count how many creators will involved",
   date_name:"Start date",
   continue_button:"Continue",

 }
});

export default strings;
