import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
 en:{
   login:"Login/Registration",
   login_button:"Join",
   password_length:"Password is too short - should be at least 6 symbol.",
   restore_password:"Forgot password",
   restore_button:"Restore",
   user_not_found:"User with this email not found please try another email or may be you are not registered",
   system_notification:"Notification",
   password_mail_notification:"The password has been sent to your email",
   title_name:"Enter business url",
   description_name:"Description",
   description_placeholder:"Please write description about your business and what you want to hear from creators",
   location_name:"Choose location",
   location_error:"Please choose location",
   time_name:"Choose time",
   amount_name:"Amount ",
   amount_placeholder:"lets count how many creators will involved",
   date_name:"Start date",
   continue_button:"Continue",
   count_of_bloggers:"Involved creators count",
   count_of_subscribers:"Approximate coverage",
   choose_payment:"Please make a payment",
   request:"Request ",
   paid:"Paid ",
   approximate_reach:"Approximate reach ",
   involved_bloggers:"Involved Creators ",
   platforms_in_use:"Platforms in use ",
   tiktok:"Tiktok ",
   instagramm:"Instagram ",
   facebook:"Facebook ",
   twitter:"Twitter ",
   list_of_bloggers:"List of Creators ",
   view:"View",
   profile:"Profile",
   detail:"Detail",
   completition:"Details about completition",
   profileInformation:"Profile Information",
   number_of_c_tasks:"Number of Completed Tasks",
   rating:"Rating",
   subscribers_p:"Subscribers",
   rate:"Rate",
   rateDescribe:"please leave detail review",
   successAction:"Success action Thanks!",
   rateAction:"Please click star to rate!",
   cantRate:"You already rate..",
   selectRole:"Select your Role",
   blogger:"Creator",
   business:"Business",
   continue:"Continue?",
   no:"no",
   yes:"yes",
   currentStep:"create video about business and upload here: ",
   socialNetwork:" (social network) ",
   currentStepAfter:" copy link and insert below inside form, then click button 'next': ",
   doneTask:"Task Submitted",
   waitingApprove:"under consideration by business",
   Offers:"Offers",
   cancel:"cancel",
   check:"check",
   dialogCheckMessage:"You have new suggestion from business please go to Contacts to discuss",
   startTask:"Start task",
   CopyUrl:"Copy url",
   next_x:"Next",
   chat_with_business:"Chat with Business",
   select_social:"Select Social Network",
   edit_social:"Edit Box",
   confirm_edit:"Confirm",
   edit_confirmation:"this field only to update purpose, try field above to add new link if previous video was banned",
   edit_button_link:"Edit Video Link",
   banBoxTitle:"This videos were banned please make new videos and upload for this social networks and insert link above to form",
   onlyLocal:"Involve only local creators",
   searchLocal:"Search only local business",

 },
 it: {
   login:"Login/Registration",
   login_button:"Join",
   password_length:"Password is too short - should be at least 6 chars minimum.",
   restore_password:"Forgot password",
   restore_button:"Restore",
   user_not_found:"User with this email not found please try another email or may be you are not registered",
   system_notification:"Notification",
   password_mail_notification:"The password has been sent to your email",
   title_name:"Name of business or url",
   description_name:"Description",
   description_placeholder:"Please write description about your business and what you want to hear from creators",
   location_name:"Chose location",
   time_name:"Choose time",
   amount_name:"Amount",
   amount_placeholder:"lets count how many creators will involved",
   date_name:"Start date",
   continue_button:"Continue",

 }
});

export default strings;
